### ISSUE TITLE
2022-23 MDE Ed-Fi Documentation

### ISSUE THREAD

**Issue by mailtokarthik2003** [mn-mde-edfi/MDE-EdFi-Documentation#37]
sir,
(2022-23 Data Mapping Matrix Ed-Fi Suite 3 v 5.2 final.xlsx)
I want  v5.3 data mapping. I am using v5.3 version .But there is not available ed-fi 0ds api java sample code for post and put any idea share me.

**Comment by mmdolbow** [comment]
I don't think this is the documentation you are looking for; the audience for this is specifically for vendors serving Minnesota local education agencies (LEAs). The spreadsheet you mention is specific to Minnesota's implementation and focuses only on our extension.

You will have better luck searching for documentation at [the Ed-Fi website](https://techdocs.ed-fi.org). For example, [this page](https://techdocs.ed-fi.org/display/ETKB/Ed-Fi+Technology+Version+Index#EdFiTechnologyVersionIndex-Data-Standard) details the versions of their data standard and ODS, and you can see the data standard maxes out at 4. In contrast, the ODS/API does have version 5.3, and [this website](https://techdocs.ed-fi.org/pages/viewpage.action?pageId=95259668) details that. There's even a [section on generating an SDK](https://techdocs.ed-fi.org/display/ODSAPIS3V53/Using+Code+Generation+to+Create+an+SDK).

Hope this helps you out.
